### ISSUE TITLE
How to evalute the results of ST-CGAN and DeshadowNet

### ISSUE THREAD

**Issue by xw-hu** [lmhieu612/FSS2SR#3]
Since there is no code provided for the ST-CGAN and DeshadowNet, how to evaluate their results on the adjusted ISTD with the image size of 256"*256?

**Comment by hieulem** [comment]
Hi Xiaowei,

We adjust the **shadow-free images** of the testing set and keep the shadow images the same. Thus you can evaluate their results using their output images.

**Comment by xw-hu** [comment]
Thanks for your reply.
