### ISSUE TITLE
Can you publish your video shadow removal datasets?

### ISSUE THREAD

**Issue by eraserNut** [lmhieu612/FSS2SR#4]
Can you publish your video shadow removal datasets with 8 paired videos?

**Comment by hieulem** [comment]
Hi, you can find it here: https://drive.google.com/file/d/1sIj9zXDxsnPR_O_yq5mHh3z7UMB6q8WV/view

However, I would recommend you to evaluate on the SBU-Timelapse dataset which include this dataset.

**Comment by Jasonx0123** [comment]
May I ask if there is any PSNR and SSIM calculation code for the test results of video shadow removal datasets?
